version: '3.8'

volumes:
  postgres_data:
  redis_data:
  bundle_cache:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - SERVICE_ROLE=web
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ./start.sh

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - SERVICE_ROLE=sidekiq
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ./start.sh

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=test
      - SERVICE_ROLE=test
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: bundle exec rspec
